linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dupl
    - dupword
    - exhaustruct
    - exportloopref  # deprecated
    - gomnd
    - gocognit
    - gocyclo
    - gocritic
    - gochecknoinits
    - funlen
    - ireturn
    - err113
    - execinquery
    - mnd
    - nestif
    - testpackage
    - paralleltest
    - prealloc
    - maintidx
    - gochecknoglobals
    - gosmopolitan
    - varnamelen
    - tagliatelle
    - lll
    - wrapcheck

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  lll:
    line-length: 160
  errcheck:
    exclude-functions:
      # Used in HTTP handlers, any error is handled by the server itself.
      - (net/http.ResponseWriter).Write
      # Never check for logger errors.
      - (github.com/go-kit/log.Logger).Log
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: true
