go:
    # Whenever the Go version is updated here, .circle/config.yml and
    # .promu-cgo.yml should also be updated.
    version: 1.21
repository:
    path: github.com/mahendrapaipuri/batchjob_monitoring
build:
    binaries:
        - name: batchjob_exporter
          path: ./cmd/batchjob_exporter
        - name: batchjob_stats
          path: ./cmd/batchjob_stats
    flags: -a -tags 'netgo osusergo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - linux/arm64
        - linux/mips
        - linux/mipsle
        - linux/mips64
        - linux/mips64le
        - linux/ppc64le
