go:
    # Whenever the Go version is updated here, .circle/config.yml and
    # .promu.yml should also be updated.
    version: 1.22
    cgo: true
repository:
    path: github.com/mahendrapaipuri/ceems
build:
    binaries:
        - name: ceems_api_server
          path: ./cmd/ceems_api_server
        - name: ceems_lb
          path: ./cmd/ceems_lb
    tags:
      all: [osusergo, netgo, static_build]
    flags: -a
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - build/config/ceems_lb/ceems_lb.yml
        - build/config/ceems_api_server/ceems_api_server.yml
        - build/config/common/web-config.yml
        - LICENSE
        - README.md
crossbuild:
    platforms:
        - linux/386
        - linux/amd64
        - linux/arm64
        - linux/mips
        - linux/mips64
        - linux/mips64le
        - linux/mipsle
        # - linux/ppc64
        - linux/ppc64le
        - linux/riscv64
        # - linux/s390x
