version: 2.1
executors:
  arm:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

jobs:
  test-arm:
    executor: arm
    steps:
      - checkout
      - run: uname -a
      # Install a specific version of Go. Everytime we bump Go toolchain version in
      # go.mod, we need to use the same version here.
      # This is to avoid weird errors like `compile: version "go1.25.1" does not match go tool version "go1.25.0"`
      # when go updates itself
      - run: |
          GO_VERSION=1.25.2
          wget -O /tmp/go${GO_VERSION}.linux-arm64.tar.gz https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf /tmp/go${GO_VERSION}.linux-arm64.tar.gz
      - run: go env
      - run: GOARCH=1 make clang
      - run: make
      - run: CGO_APPS=1 make

workflows:
  ceems:
    jobs:
      - test-arm:
          filters:
            tags:
              only: /.*/
