version: 2.1
orbs:
  prometheus: prometheus/prometheus@0.17.1
executors:
  # Whenever the Go version is updated here, .promu.yml and .promu-cgo.yml
  # should also be updated.
  golang:
    docker:
      - image: cimg/go:1.21
  arm:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium

jobs:
  test:
    executor: golang
    steps:
      - prometheus/setup_environment
      - run: go mod download
      - run: make
      - run: CGO_ENABLED=1 make
  test-arm:
    executor: arm
    steps:
      - checkout
      - run: uname -a
      - run: make test-e2e
      - run: CGO_ENBLED=1 make test-e2e
  build:
    machine:
      image: ubuntu-2204:current
    parallelism: 3
    steps:
      - prometheus/setup_environment
      - run: docker run --privileged linuxkit/binfmt:af88a591f9cc896a52ce596b9cf7ca26a061ef97
      - run: promu crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX
      # Replace default CGO_ENABLED before we run CGO. There is no way to inject this env 
      # variable into golang-builder container. So we artificially replace the default
      # CGO_ENABLED variable in Makefile and run CGO promu
      - run: sed -i -e 's/CGO_ENABLED             ?= 0/CGO_ENABLED             ?= 1/g' Makefile
      - run: cat Makefile
      - run: promu --config .promu-cgo.yml crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX
      - persist_to_workspace:
          root: .
          paths:
            - .build
      - store_artifacts:
          path: .build
          destination: /build
workflows:
  version: 2
  batchjob_exporter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - test-arm:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - prometheus/publish_release:
          context: org-context
          docker_hub_organization: ''
          quay_io_organization: ''
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
