# Packages that are used exclusively in e2e tests are build here
go:
    # Whenever the Go version is updated here, .circle/config.yml and
    # .promu-cgo.yml should also be updated.
    version: 1.24
    cgo: true
repository:
    path: github.com/mahendrapaipuri/ceems
build:
    binaries:
        - name: ceems_api_server
          path: ./cmd/ceems_api_server
    tags:
      all: [osusergo, netgo, static_build]
    flags: -a
