go:
    # Whenever the Go version is updated here, .circle/config.yml and
    # .promu-cgo.yml should also be updated.
    version: 1.23
repository:
    path: github.com/mahendrapaipuri/ceems
build:
    binaries:
        - name: ceems_exporter
          path: ./cmd/ceems_exporter
        - name: ceems_tool
          path: ./cmd/ceems_tool
        - name: cacct
          path: ./cmd/cacct
        - name: redfish_proxy
          path: ./cmd/redfish_proxy
    tags:
      # The tag `test` is used in cacct binary to compile
      # e2e test related code for testing in CI. This file
      # MUST NOT BE COMPILED for production builds and so,
      # we remove it in CI for release builds
      all: [osusergo, netgo, static_build, test]
    flags: -a
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - build/config/ceems_exporter/redfish_exporter_config.yml
        - build/config/redfish_proxy/redfish_proxy.yml
        - build/config/cacct/cacct.yml
        - build/config/web-config.yml
        - LICENSE
        - README.md
crossbuild:
    platforms:
        - linux/386
        - linux/amd64
        - linux/arm64
        - linux/mips
        - linux/mips64
        - linux/mips64le
        - linux/mipsle
        # - linux/ppc64
        - linux/ppc64le
        - linux/riscv64
        # - linux/s390x
