#!/usr/bin/env python3

import sys
import json


def ordered(obj):
    "Sort dict recursively"
    if isinstance(obj, dict):
        return sorted((k, ordered(v)) for k, v in obj.items())
    if isinstance(obj, list):
        return sorted(ordered(x) for x in obj)
    else:
        return obj


def main():
    if len(sys.argv) < 3:
        sys.exit('Two arguments needed')

    # Get prom query result
    query_type = sys.argv[1]
    query_result = sys.argv[2]

    # Read file contents into dicts
    try:
        qr = json.loads(query_result)
        value = qr['data']['result'][0]['value'][1]

        print(f'Number of series found for {query_type} are: {value}')
    except Exception as e:
        print(e)
        sys.exit(1)


if __name__ == '__main__':
    main()
