name: Release

on:
  push:
    # Run workflow on new tags
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test-lint:
    uses: ./.github/workflows/step_tests-lint.yml

  test-unit:
    needs: [test-lint]
    uses: ./.github/workflows/step_tests-unit.yml

  test-e2e:
    needs: [test-lint]
    uses: ./.github/workflows/step_tests-e2e.yml

  build:
    needs: [test-unit, test-e2e]
    uses: ./.github/workflows/step_build.yml

  cross-build:
    needs: [build]
    uses: ./.github/workflows/step_cross-build.yml

  packaging:
    needs: [cross-build]
    uses: ./.github/workflows/step_packaging.yml

  publish:
    needs: [packaging]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install promu
        run: |
          make promu
          go mod download

      - name: Download release artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: .tarballs
      
      - name: Publish release
        run: promu release .tarballs
