name: build
run-name: Build

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install promu
        run: |
          make promu
          go mod download

      # This is intended to address disk space issues that have surfaced
      # intermittently during CI -
      # https://github.com/actions/runner-images/issues/2840#issuecomment-1284059930
      # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
      # We cannot delete "$AGENT_TOOLSDIRECTORY" as Go is in the cache and we need
      # working go installation for crossbuild target.
      - name: Free up space in /dev/root
        run: |
            echo "Disk usage before clean up:"
            df -h
            echo "$AGENT_TOOLSDIRECTORY"
            sudo rm -rf /usr/share/dotnet
            echo "Disk usage after clean up:"
            df -h

      # Cross compile for only AMD and ARM archs in CI to reduce CI time and artifacts size
      # We will compile for all supported archs in release workflow
      - name: Cross compile Go packages
        run: |
          echo "Disk usage before building:"
          df -h
          make crossbuild
          echo "Disk usage after building:"
          df -h
          docker ps -a
          docker volume ls

      - name: Cross compile CGo packages
        run: |
          echo "Disk usage before building:"
          df -h
          CGO_APPS=1 make crossbuild
          echo "Disk usage after building:"
          df -h
          docker ps -a
          docker volume ls

      - name: Upload go build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          # Here we add .tarballs to path even if there is no .tarballs. This is to be
          # consistent with cross-build step so that on download artifact we dont have to
          # provide path argument.
          path: |
            .build
            .tarballs
          retention-days: 3
          include-hidden-files: true
