name: cross-build
run-name: Cross build

on:
  workflow_call:

jobs:
  cross-build:
    name: cross-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install promu
        run: |
          make promu
          go mod download

      # These steps are taken from https://circleci.com/developer/orbs/orb/prometheus/prometheus#jobs-publish_release
      - name: Setup build environment
        run: |
          docker version
          docker run --privileged linuxkit/binfmt:v0.8

      - name: Cross compile Go packages
        run: make crossbuild

      - name: Cross compile CGo packages
        run: CGO_APPS=1 make crossbuild
      
      - name: Create tarballs and checksums
        run: |
          promu crossbuild tarballs
          promu checksum .tarballs

      - name: Upload go build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .build
            .tarballs
          retention-days: 1
          include-hidden-files: true
