name: unit-tests
run-name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Setup clang
        run: ./scripts/install_clang.sh

      - name: Run checkmetrics, checkrules and checkbpf
        run: make checkmetrics checkrules checkbpf

      - name: Run unit tests for Go packages
        run: make test

      - name: Run unit tests for CGo packages
        run: CGO_BUILD=1 make test

      - name: Merge coverage files
        run: |
          # Make global coverage report
          make coverage

          # Remove testdata that contains too many files
          rm -rf pkg/collector/testdata

      # Upstream package will not keep the format of README
      # PR -> https://github.com/AlexBeauchemin/gobadge/pull/7
      # - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
      #   uses: tj-actions/coverage-badge-go@v2
      #   with:
      #     filename: coverage.out
      #     link: https://github.com/mahendrapaipuri/ceems/actions/workflows/ci.yml?query=branch%3Amain

      - name: Go coverage badge
        run: |
          # Install our custom badge updater
          git clone https://github.com/mahendrapaipuri/gobadge
          cd gobadge
          go install .
          cd ..

          # Create/Update badge
          gobadge -target README.md -filename coverage.out -link https://github.com/mahendrapaipuri/ceems/actions/workflows/ci.yml?query=branch%3Amain
          gobadge -target website/docs/00-introduction.md -filename coverage.out -link https://github.com/mahendrapaipuri/ceems/actions/workflows/ci.yml?query=branch%3Amain

          # Check diff on README
          git diff README.md
          git diff website/docs/00-introduction.md

      - name: Verify Changed files
        id: verify-changed-files
        run: |
          # If there are no changes exit code will be 0 and 1 if there are changes
          if git diff --exit-code README.md website/docs/00-introduction.md > /dev/null; then
              echo "files_changed=false" >> $GITHUB_OUTPUT
          else
              echo "files_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "bot@ceems.com"
          git config --local user.name "CEEMS Bot"
          git add README.md website/docs/00-introduction.md
          git commit -m "chore: Updated coverage badge" -s

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true' && github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
