name: unit-tests
run-name: Unit Tests

on:
  workflow_call:

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install promu
        run: |
          make promu
          go mod download

      - name: Run unit tests for Go packages
        run: make test

      - name: Run unit tests for CGo packages
        run: CGO_BUILD=1 make test
