name: build
run-name: Build

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install promu
        run: |
          make promu
          go mod download

      # Cross compile for only AMD and ARM archs in CI to reduce CI time and artifacts size
      # We will compile for all supported archs in release workflow
      - name: Cross compile Go packages
        run: promu --config .promu-go.yml crossbuild -v -p linux/amd64 linux/arm64

      - name: Cross compile CGo packages
        run: |
          sed -i -e 's/CGO_BUILD               ?= 0/CGO_BUILD               ?= 1/g' Makefile
          promu --config .promu-cgo.yml crossbuild -v -p linux/amd64 linux/arm64

      - name: Upload go build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-go-artifacts
          path: |
            .build
            .tarballs
          retention-days: 3
