name: packaging
run-name: Packaging

on:
  workflow_call:

jobs:
  packaging:
    name: packaging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    env:
      GOOS: linux
      GOARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      # Build RPM and DEB packages
      - name: Build deb and rpm packages
        run: |
          export GOOS=${{ env.GOOS }}
          export GOARCH=${{ env.GOARCH }}
          export TAG_NAME=${{ github.ref_name }}
          # Strip v from tag name, eg v0.1.0 -> 0.1.0
          export CEEMS_VERSION=$(echo "${TAG_NAME//v}")

          # Ensure target directory exists
          mkdir -p .tarballs

          # deb packages
          nfpm pkg --config build/package/ceems_exporter/nfpm.yml --packager deb --target .tarballs/ceems_exporter-${CEEMS_VERSION}-${{ env.GOOS }}-${{ env.GOARCH }}.deb
          nfpm pkg --config build/package/ceems_api_server/nfpm.yml --packager deb --target .tarballs/ceems_api_server-${CEEMS_VERSION}-${{ env.GOOS }}-${{ env.GOARCH }}.deb
          nfpm pkg --config build/package/ceems_lb/nfpm.yml --packager deb --target .tarballs/ceems_lb-${CEEMS_VERSION}-${{ env.GOOS }}-${{ env.GOARCH }}.deb

          # rpm packages
          nfpm pkg --config build/package/ceems_exporter/nfpm.yml --packager rpm --target .tarballs/ceems_exporter-${CEEMS_VERSION}-${{ env.GOOS }}-${{ env.GOARCH }}.rpm
          nfpm pkg --config build/package/ceems_api_server/nfpm.yml --packager rpm --target .tarballs/ceems_api_server-${CEEMS_VERSION}-${{ env.GOOS }}-${{ env.GOARCH }}.rpm
          nfpm pkg --config build/package/ceems_lb/nfpm.yml --packager rpm --target .tarballs/ceems_lb-${CEEMS_VERSION}-${{ env.GOOS }}-${{ env.GOARCH }}.rpm

          # Check artifacts
          ls -la .tarballs

      - name: Upload go build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-go-artifacts
          path: .tarballs
          retention-days: 1
