name: e2e-tests
run-name: End2End Tests

on:
  workflow_call:

jobs:
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Setup clang 18
        run: ./scripts/install_clang.sh

      - name: Run e2e tests for Go packages
        run: make test-e2e

      - name: Run e2e tests for CGo packages
        run: CGO_BUILD=1 make test-e2e
