# This action is synced from https://github.com/prometheus/prometheus
name: golangci-lint
run-name: Lint

on:
  workflow_call:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Create a sample object file
        run: |
          mkdir -p pkg/collector/bpf/objs
          touch pkg/collector/bpf/objs/sample.o

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
          args: --timeout=5m
