name: packaging
run-name: Packaging

on:
  workflow_call:

jobs:
  packaging:
    name: packaging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install nfpm
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      - name: Download go build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Get version
        id: vars
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF_TYPE}" == "tag" ]]; then
            REF_NAME=$(echo "${GITHUB_REF_NAME//\//-}")
            CEEMS_VERSION=$(echo "${REF_NAME//v}")
            echo "version=${CEEMS_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
          fi

      # Build RPM and DEB packages
      - name: Build deb and rpm packages
        run: ./scripts/packaging.sh -v ${{ steps.vars.outputs.version }} -b

      - name: Test deb packages
        run: ./scripts/packaging.sh -v ${{ steps.vars.outputs.version }} -t

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: .tarballs
          retention-days: 1
          include-hidden-files: true
