name: tests
on:
  push:
    branches:
      - "main"
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/test.yml"
  pull_request:

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install promu
        run: |
          make promu
          go mod download

      - name: Run test for pure Go packages
        run: make

      - name: Run test for CGo packages
        run: CGO_BUILD=1 make
