name: tests
on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - "scripts/errcheck_excludes.txt"
      - ".github/workflows/golangci-lint.yml"
      - ".golangci.yml"
  pull_request:

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install promu
        run: |
          make promu
          go mod download

      - name: Run test for pure Go packages
        run: make

      - name: Run test for CGo packages
        run: CGO_BUILD=1 make
  
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
            go-version: 1.21.x

      - name: Install promu
        run: |
          make promu
          go mod download

      - name: Cross compile Go packages
        run: promu --config .promu-go.yml crossbuild -v

      - name: Cross compile CGo packages
        run: |
          sed -i -e 's/CGO_BUILD               ?= 0/CGO_BUILD               ?= 1/g' Makefile
          promu --config .promu-cgo.yml crossbuild -v
      
      - name: Upload UI Test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-output
          path: .build
          retention-days: 3
